version: '3.8'

services:
  web:
    image: ${imagedocker}
   # command: #gunicorn screencast.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/notes_api/
      - static:/usr/src/notes_api/static/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgreuser
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=notesData

volumes:
  postgres_data:
  static: