version: '3.8'

services:
  web:
    build: .
   # command: #gunicorn screencast.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/notes_api/
      - static:/usr/src/notes_api/static/
      - /var/log/containerlogs:/var/log/containerlogs
    ports:
      - 8000:80
    env_file:
      - ./.env.dev
    depends_on:
      - db
  clientfluent0:
    build: ./fluentd
    volumes:
      - /var/log/containerlogs:/var/log/conatinerlogs
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgreuser
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=notesData

volumes:
  postgres_data:
  static:
